export const table = [
  {
    label: 'Force',
    score: 8,
    racial: 0,
    value: 8,
    mod: -1,
    id: 1,
    bonus: 0,
    tooltip: 'str'
  }, {
    label: 'Dextérité',
    score: 8,
    racial: 0,
    value: 8,
    mod: -1,
    id: 2,
    bonus: 0,
    tooltip: 'dex'
  }, {
    label: 'Constitution',
    score: 8,
    racial: 0,
    value: 8,
    mod: -1,
    id: 3,
    bonus: 0,
    tooltip: 'con'
  }, {
    label: 'Intelligence',
    score: 8,
    racial: 0,
    value: 8,
    mod: -1,
    id: 4,
    bonus: 0,
    tooltip: 'int'
  }, {
    label: 'Sagesse',
    score: 8,
    racial: 0,
    value: 8,
    mod: -1,
    id: 5,
    bonus: 0,
    tooltip: 'sag'
  }, {
    label: 'Charisme',
    score: 8,
    racial: 0,
    value: 8,
    mod: -1,
    id: 6,
    bonus: 0,
    tooltip: 'cha'
  }
];
